[webservers]

web-1 ansible_host=93.77.183.26 fqdn=fhm8ffe4afcip9onnahl.auto.internal
web-2 ansible_host=93.77.189.152 fqdn=fhmf07fqj1784958jifp.auto.internal

[db]

main ansible_host=93.77.191.206 fqdn=fhmp5vmloplq1vrbia0g.auto.internal
replica ansible_host=89.169.128.225 fqdn=fhmhblfbhggkth2g0q0h.auto.internal

[storage]

storage ansible_host=89.169.154.155 fqdn=fhmubqnum6rm6k9ga84e.auto.internal
